### ISSUE TITLE
theano and kears  version

### ISSUE THREAD

**Issue by Hjy20255** [julienr/agro_esann16#1]
hi~
thanks for your open code.i can run run_experiments_rot90.py .I get cnn.zip histnn.zip and merged_nn.zip .But when i run predict_img.py, i get an error "model_from_config() got an unexpected keyword argument 'custom_objects'".
i want to know which version of theano  and keras.

**Comment by julienr** [comment]
I think I used keras 1.0 and Theano 0.8. Which versions are you using ?

**Comment by Hjy20255** [comment]
keras 0.2.0  theano 0.8.2 
In your code ，i found  print_layer_shapes() function.Keras-0.2.0 has this function .SO I use keras-0.2.0.
i modified agronn/keras_utils.py code.
 model = keras.models.model_from_config(config,custom_objects=custom_layers)  to  model = keras.models.model_from_config(config,custom_layers=custom_layers) 
Finally,it can run successfully.

**Comment by julienr** [comment]
Great that you got it to work. keras 0.2 seems pretty old, I think I started the project on 0.3 and then updated to 1.0 at the end.

Let me know if you have any other questions.
